In [1]:
a =3
b = 4
c = a**b
print(c)

81


# addition +
# multiplication *
# substraction -
# division /
# remainder %
# power **
# floor division //

a + b


In [4]:
r =  a - b
print (r)

-1


In [6]:
z = a % b
print(z)

3


In [7]:
a ** b

81

In [8]:
a // b


0

In [9]:
 i = 52
 j = 56
k = 64
m = i ** j // k
print(m)

19498772380737955855029406086015905908179064742141477879768789357285222141704467212293032116224


In [10]:
i // k * k

0

In [12]:
a = "binnith "
b = "reddy"
c = a + b
print(c) 

binnith reddy


In [13]:
type(z)


int

In [18]:
m = (i-j)//
print(m)

-1


In [26]:
a = 45
b = 25
a < b

False

In [27]:
a > b


True

In [28]:
4 > 6

False

In [35]:
x = 34
y = 34
c = x + y
print(c)

68


In [38]:
x != y

False

In [39]:
x == y

True

In [40]:
x = y

In [41]:
h = 56
g = "wet"


In [42]:
h == g

False

In [43]:
 (a>b) and (b>a)

False

In [44]:
(a>b) or (b>a)

True

In [ ]:
t & t = t
t & f = f
f & t = f
f & t = f

In [ ]:
t or t = t
t or f = t
f or t = t
f or t = f

In [ ]:
s


In [1]:
{40, 60, 70, 77, 80}

{40, 60, 70, 77, 80}

In [2]:
s.difference(y)

NameError: name 's' is not defined

In [3]:
s = {40, 60, 70, 77, 80}

In [4]:
s.difference(y)

NameError: name 'y' is not defined

In [5]:
y = {80, 60, 77, 70, 68}

In [6]:
s.difference(y)

{40}

In [7]:
y.intersection(s)

{60, 70, 77, 80}

In [8]:
s.union(y)

{40, 60, 68, 70, 77, 80}

In [9]:
x = {54, 65, 78, 48}


In [10]:
s.union(x)

{40, 48, 54, 60, 65, 70, 77, 78, 80}

In [19]:
x=90
if x>=90:
    print('gradeA')
elif x>=80:
    print("grade B")

gradeA


In [1]:
d = {'a':85,'b':7,'c':87}
d

{'a': 85, 'b': 7, 'c': 87}

In [3]:
type(d)
dictionary are mutuable objects


SyntaxError: invalid syntax (2890821718.py, line 2)

In [5]:
d['a']

85

In [10]:
d = {'104':9,'105':1,'106':5}

In [14]:
d.update({10:8})

In [15]:
d

{'104': 9, '105': 1, '106': 5, 10: 8}

In [22]:
del d[('104'9)]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3926429651.py, line 1)

In [23]:
d.update({'104': 5000})

In [24]:
d

{'105': 1, '106': 5, 10: 8, '104': 5000}

In [28]:
del d['105']

KeyError: '105'

In [29]:
d.get(105)

In [31]:
d

{'106': 5, 10: 8, '104': 5000}

In [32]:
d

{'106': 5, 10: 8, '104': 5000}

In [33]:
d ={'101':7,'102':8,'103':9}


In [34]:
type(d)

dict

In [38]:
d.update({'101': 80})

In [39]:
d

{'101': 80, '102': 8, '103': 9, 101: 80}

In [40]:
d.get('101')

80

In [41]:
del d['101']

In [42]:
d

{'102': 8, '103': 9, 101: 80}

In [43]:
d[103] = [1000,2000,6000]

In [44]:
d

{'102': 8, '103': 9, 101: 80, 103: [1000, 2000, 6000]}

In [49]:
d.get(103)

[1000, 2000, 6000]

In [6]:
d[103][0]

NameError: name 'd' is not defined

In [5]:
d[103][1]

NameError: name 'd' is not defined

In [8]:
d[103][0:3]

NameError: name 'd' is not defined

In [10]:
d.update({104:[7000,8000,9000]})

NameError: name 'd' is not defined

In [11]:
d

NameError: name 'd' is not defined

In [12]:
d = {'105': 1, '106': 5, 10: 8, '104': 5000}


In [15]:
d.update({'104':[7000,8000,9000]})

In [16]:
d

{'105': 1, '106': 5, 10: 8, '104': [7000, 8000, 9000], 104: [7000, 8000, 9000]}

In [19]:
d[101]={50:[7,8,9,10],'apple':(20,10,70,[90,180,270])}

In [20]:
d

{'105': 1,
 '106': 5,
 10: 8,
 '104': [7000, 8000, 9000],
 104: [7000, 8000, 9000],
 101: {50: [7, 8, 9, 10], 'apple': (20, 10, 70, [90, 180, 270])}}

In [21]:
d[105]={'a':{30,50,70},'b':(1000,5000,7000,9000),'c':['k',{'L':[11,22],'M':(77,88)},'N']}

In [22]:
d

{'105': 1,
 '106': 5,
 10: 8,
 '104': [7000, 8000, 9000],
 104: [7000, 8000, 9000],
 101: {50: [7, 8, 9, 10], 'apple': (20, 10, 70, [90, 180, 270])},
 105: {'a': {30, 50, 70},
  'b': (1000, 5000, 7000, 9000),
  'c': ['k', {'L': [11, 22], 'M': (77, 88)}, 'N']}}

In [31]:
d[101]['apple'][3][0]

90

In [ ]:
d[101]

In [ ]:
if condition:
    task1 block of code 
elif condition2:
    task2 block of code
elif condition3:
    task3 block of code
else:
    task4 block of code
    

In [1]:
x=9
if x%2==0:
    print("even")
else:
    print("odd")

odd


In [8]:
y= 'india'
y

'india'

In [9]:
y.isdigit()

False

In [7]:
y.isalpha()

True

In [16]:
name='reddy'

In [20]:
if name.isalpha()==True:
    print('Accept')
else:
    print('name should not contain digits and symbols')

Accept


In [22]:
name.isalpha()

True

In [23]:
name.lower()


'reddy'

In [41]:
x='Telangana'
if x[0]=='T':
    print('Yes')
else:
    print('No')

Yes


In [43]:
x

'Telangana'

In [44]:
x[0].lower()=='t'

True

In [50]:
x = input("enter any word")
if x[0].lower() == 't' or x[0].lower()=='s' or x[0].lower()=='h':
    print("True")
else:
    print("False")
    

enter any word lion


False


In [1]:
if x[0].lower() in ('s','h','m'):
    print('yes')
else: 
    print('no'

SyntaxError: incomplete input (3368511227.py, line 4)

In [ ]:
x=5
while x<35:
    print('yes')
    

In [ ]:
x=3
while x<10:
    print('yes',x)
    x=x-5

In [2]:
x=35
while x>10:
    print('yes',x)
    x=x-5

yes 35
yes 30
yes 25
yes 20
yes 15


In [3]:
x=40
while x<46:
    print('yes',x)
    x=x+1

yes 40
yes 41
yes 42
yes 43
yes 44
yes 45


In [4]:
y=[40,20,80,50,30,60,90]
y

[40, 20, 80, 50, 30, 60, 90]

In [5]:
50+5


55

# day 8

In [3]:
def function(parameter):
    #block of code
    return output

In [4]:
def calArea(r):
    a=3.14*r*r
    return a

In [5]:
calArea(r=10)

314.0

In [7]:
w=calArea(r=10)
w

314.0

In [8]:
type(w)

float

In [21]:
def d_to_inr(x):
    return(x*85)

In [22]:
a=d_to_inr(15)
a

1275

In [23]:
b=d_to_inr(20)
b

1700

In [24]:
b+a

2975

In [25]:
type(b)

int

In [32]:
def aor(l,w):
    area=l*w
    return area

In [43]:
def area(radius,length,width):
    aoc=3.14*radius*radius
    aor= length*width
    return aor,aoc

In [45]:
d=area(radius=10,length=20,width=5)

In [46]:
print(d)

(100, 314.0)


In [47]:
type(d)

tuple

In [48]:
d[1]

314.0

In [49]:
s=area(radius=10,length=20,width=5)
type(s)

tuple

In [50]:
t='HyderabAAd 500008 Telangana'
t

'HyderabAAd 500008 Telangana'

In [58]:
alpha_count = sum(c.isaplha() for c in t)
digit_count = sum(c.isdigit() for c in t)
print(f"Alphabetic characters: {alpha_count}")
print(f"Numeric characters: {digit_count}")

AttributeError: 'str' object has no attribute 'isaplha'

In [53]:
def count_num_alpha(x):
    c=0
    d=0
    for i in x:
        if i.isalpha():
            c+=1
        elif i.isnumeric():
            d+=1
    return {'Number of alphabets':c,'Number of digits':d}

In [57]:
count_num_alpha(t)

{'Number of alphabets': 19, 'Number of digits': 6}

In [62]:
x='Hyderabad 500008 telangana '
def remove_num(x):

    y=''
    for i in x:
        if i.isdigit()==False:
            y+=i
        return y

In [63]:
remove_num(t)

'H'

# Day 9 

In [4]:
import numpy as np
j=[4,6,5,1,2]
type(j)


list

numpy is used for array operations 
pandas is used for Data manipulation and analysis
matplotlib and Seaborn are used in Graphical Analysis
sklearn is used in machine learning algorithms and techniques
stat models is used in  statistical analysis
scipy  is used in statistical analysis

In [4]:
np.array(j)

array([4, 6, 5, 1, 2])

In [5]:
tuple(j)

(4, 6, 5, 1, 2)

In [6]:
d=np.array(j)
d

array([4, 6, 5, 1, 2])

In [7]:
type(d)

numpy.ndarray

In [8]:
d

array([4, 6, 5, 1, 2])

In [9]:
d.shape

(5,)

In [10]:
j

[4, 6, 5, 1, 2]

In [11]:
d.ndim

1

In [12]:
d.size

5

In [13]:
s=[[4,8,90,12],[56,78,54,20],[67,98,80,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 98, 80, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [14]:
type(s)

list

In [5]:
arr1=np.array(s)
arr1

NameError: name 'np' is not defined

In [18]:
arr1.shape

(5, 4)

In [19]:
arr1.size

20

In [20]:
arr1.ndim

2

In [29]:
arr1.reshape(4,5)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 98, 80, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [30]:
arr1.shape

(5, 4)

In [31]:
arr1.ndim


2

In [32]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 98]],

       [[80, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [33]:
k.size

20

In [34]:
k.ndim

3

In [35]:
k.shape

(2, 2, 5)

In [4]:
arr1

NameError: name 'arr1' is not defined

In [7]:
range(5,20)

range(5, 20)

In [8]:
m=[3,4,5,6,7,8,9]
m

[3, 4, 5, 6, 7, 8, 9]

In [9]:
list(range(3,101))


[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

In [11]:
list(range(3,101,3))


[3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99]

In [12]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [13]:
list(range(-1,-19,-1))

[-1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -12,
 -13,
 -14,
 -15,
 -16,
 -17,
 -18]

In [15]:
list(range(-1,-19,-2))

[-1, -3, -5, -7, -9, -11, -13, -15, -17]

In [17]:
np.arange(2.5,5,0.5)

NameError: name 'np' is not defined

In [18]:
range(5,50,5)


range(5, 50, 5)

In [20]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [6]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [25]:
even_pos = []
odd_pos = []
j = [1,2,3,4,5]
for i in range(len(j)):
    if i % 2 == 0:
        even_pos.append(i)
    else:
        odd_pos.append(i)
print("Even  position Number:",even_pos)
print("Odd position Number:",odd_pos)


Even  position Number: [0, 2, 4]
Odd position Number: [1, 3]


# Distribution|


In [7]:
np.median(j)

62.0

In [10]:
import numpy as np

In [10]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [11]:
np.mean(d)

40.0

In [12]:
np.median(d)

40.0

In [14]:
np.max(d)

70

In [15]:
np.min(d)

10

In [16]:
np.quantile(d,0.25)

30.0

In [18]:
r=np.random.rand(10,5)

In [19]:

np.random.rand(100)

array([0.53347472, 0.62434912, 0.92707904, 0.67148365, 0.90636583,
       0.78415671, 0.80243643, 0.10411747, 0.85132756, 0.13932163,
       0.06345347, 0.25861719, 0.38983066, 0.66356236, 0.36733223,
       0.87999898, 0.99378306, 0.78628328, 0.3809913 , 0.57793028,
       0.67078744, 0.80575655, 0.62559087, 0.77121264, 0.98767992,
       0.61383787, 0.16357963, 0.55711932, 0.49185069, 0.9196626 ,
       0.28406265, 0.13688747, 0.44455313, 0.12643682, 0.56151829,
       0.17929608, 0.57666158, 0.83161078, 0.45223008, 0.28368498,
       0.70317883, 0.75203964, 0.7102554 , 0.44596289, 0.1029511 ,
       0.98809961, 0.48648537, 0.94992338, 0.02692679, 0.66501093,
       0.71404551, 0.60307946, 0.60966848, 0.86332102, 0.10982391,
       0.44124066, 0.97992493, 0.31054347, 0.25906301, 0.47202307,
       0.09731799, 0.03297855, 0.69861748, 0.87567338, 0.38028042,
       0.22266215, 0.0782236 , 0.34398804, 0.35207613, 0.80491206,
       0.23933781, 0.85294354, 0.49052214, 0.52012868, 0.12916

In [20]:
r.shape

(10, 5)

In [21]:
r.ndim

2

In [22]:
r.size

50

In [24]:
np.random.randn(10,4)

array([[-0.66754017,  1.00670536, -0.14817622,  0.06640884],
       [ 1.00680028,  2.14776861, -0.49249617,  1.15973406],
       [-0.68366868,  0.73589138, -2.46065079,  0.96878586],
       [ 0.48345871,  1.06921066, -1.76592977,  1.17660859],
       [-0.70965659,  0.32417862, -1.04772154,  0.36553318],
       [ 0.64633073,  0.16732216, -0.76646188,  1.55163661],
       [-0.53432359, -0.71184088, -1.09127139, -0.37620182],
       [-0.39638394,  2.05640657, -1.79764305, -0.99718156],
       [-0.24145777,  0.73226212,  0.63617364, -1.79154887],
       [-1.79678964,  0.84981547, -0.03651313,  1.01649485]])

In [25]:
np.random.randn(30,1)

array([[ 0.40183227],
       [-0.46156589],
       [ 0.57348107],
       [ 0.71311403],
       [ 0.21976413],
       [-1.32958186],
       [ 0.48977819],
       [ 0.26883347],
       [-0.08594325],
       [-0.30998523],
       [-0.81414488],
       [ 1.55589674],
       [-0.61113138],
       [ 0.23214565],
       [-0.84810448],
       [-0.60830433],
       [ 0.38684873],
       [ 0.41478253],
       [-0.30683251],
       [ 1.18614532],
       [-0.36506255],
       [ 1.38768317],
       [-0.51777145],
       [ 1.27363773],
       [ 0.15189973],
       [-0.51989517],
       [ 0.53167484],
       [ 0.7272459 ],
       [ 0.80142666],
       [-0.00227117]])

In [26]:
np.random.normal(10,2,(4,5))

array([[ 7.47169394, 11.4450046 ,  9.25093136,  8.0673772 , 10.40091595],
       [10.21294017,  9.16513744, 12.94514757,  7.95503803,  8.3178834 ],
       [12.42050297,  9.12211077,  9.36119928,  8.81923422,  4.40592208],
       [ 6.21258363,  8.7680165 ,  8.49946781,  6.76251452,  5.28377386]])

In [27]:
np.random.normal(40,5)

42.90104759482502

In [1]:
np.random.randint


NameError: name 'np' is not defined

# Day 10


In [1]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [3]:
updated=[]
for i in h:
    updated.append(7+i)
print("Updated list: ",updated)

Updated list:  [37, 27, 12, 15, 16]


In [4]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [6]:
d=[]
for i in s:
    d.append(i*i)
print("Squares of number in tuple:",d)

Squares of number in tuple: [36, 4, 9, 81, 49, 25, 64]


In [7]:
e=tuple(d)
e

(36, 4, 9, 81, 49, 25, 64)

In [11]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [12]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [14]:
t=arr+7
t

array([ 27,  57,  37,  77,  87,  47,  43,  61,  30, 105])

In [15]:
arr*5

array([100, 250, 150, 350, 400, 200, 180, 270, 115, 490])

In [18]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [19]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [21]:
k=arr
k

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [22]:
k

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [25]:
index=[]
for i in range(len(k)):
    if k[i]>50:
        index.append(i)
index

[3, 4, 7, 9]

In [1]:
np.where(arr>50)


NameError: name 'np' is not defined

In [5]:
import pandas as pd
import numpy as np

In [6]:
a=np.array([20,46,87,6,3,4,9,454,96,3])

In [7]:
a

array([ 20,  46,  87,   6,   3,   4,   9, 454,  96,   3])

In [8]:
a[-5:-12:-1]

array([ 4,  3,  6, 87, 46, 20])

In [9]:
a.ndim

1

In [14]:
np.random.seed(94)
b=np.random.randint(45,70,(7,8))
b

array([[63, 45, 50, 48, 63, 67, 69, 64],
       [51, 61, 53, 52, 61, 63, 68, 54],
       [59, 46, 53, 55, 68, 45, 56, 69],
       [69, 53, 48, 60, 58, 56, 51, 58],
       [59, 47, 68, 60, 47, 66, 58, 45],
       [59, 46, 45, 46, 52, 64, 62, 63],
       [56, 49, 63, 65, 62, 53, 60, 55]])

In [16]:
b[2] # accessing 2nd row

array([59, 46, 53, 55, 68, 45, 56, 69])

In [17]:
b[:,7] #accessing the 7th coloumn


array([64, 54, 69, 58, 45, 63, 55])

In [18]:
b[-4] #accessing the 4th row

array([69, 53, 48, 60, 58, 56, 51, 58])

In [20]:
b[1,3]#accessing the  1st row and 3 column position

52

In [22]:
b[5,6] #accessing the 5th row and 6th column position

62

In [23]:
b[:,3] # accessing the 3rd column

array([48, 52, 55, 60, 60, 46, 65])

In [24]:
b

array([[63, 45, 50, 48, 63, 67, 69, 64],
       [51, 61, 53, 52, 61, 63, 68, 54],
       [59, 46, 53, 55, 68, 45, 56, 69],
       [69, 53, 48, 60, 58, 56, 51, 58],
       [59, 47, 68, 60, 47, 66, 58, 45],
       [59, 46, 45, 46, 52, 64, 62, 63],
       [56, 49, 63, 65, 62, 53, 60, 55]])

In [25]:
b[2]

array([59, 46, 53, 55, 68, 45, 56, 69])

In [29]:
b[2,1:6]

array([46, 53, 55, 68, 45])

In [31]:
array[row_start : row-end : row-step]

NameError: name 'array' is not defined

In [32]:
b

array([[63, 45, 50, 48, 63, 67, 69, 64],
       [51, 61, 53, 52, 61, 63, 68, 54],
       [59, 46, 53, 55, 68, 45, 56, 69],
       [69, 53, 48, 60, 58, 56, 51, 58],
       [59, 47, 68, 60, 47, 66, 58, 45],
       [59, 46, 45, 46, 52, 64, 62, 63],
       [56, 49, 63, 65, 62, 53, 60, 55]])

In [33]:
b[1:6]

array([[51, 61, 53, 52, 61, 63, 68, 54],
       [59, 46, 53, 55, 68, 45, 56, 69],
       [69, 53, 48, 60, 58, 56, 51, 58],
       [59, 47, 68, 60, 47, 66, 58, 45],
       [59, 46, 45, 46, 52, 64, 62, 63]])

In [41]:
b[2:4]

array([[59, 46, 53, 55, 68, 45, 56, 69],
       [69, 53, 48, 60, 58, 56, 51, 58]])

In [43]:
b[1:6:2,1:6]

array([[61, 53, 52, 61, 63],
       [53, 48, 60, 58, 56],
       [46, 45, 46, 52, 64]])

In [46]:
b[1:6:2,2:6]

array([[53, 52, 61, 63],
       [48, 60, 58, 56],
       [45, 46, 52, 64]])

In [47]:
b[3:6,2:6]

array([[48, 60, 58, 56],
       [68, 60, 47, 66],
       [45, 46, 52, 64]])

In [48]:
b


array([[63, 45, 50, 48, 63, 67, 69, 64],
       [51, 61, 53, 52, 61, 63, 68, 54],
       [59, 46, 53, 55, 68, 45, 56, 69],
       [69, 53, 48, 60, 58, 56, 51, 58],
       [59, 47, 68, 60, 47, 66, 58, 45],
       [59, 46, 45, 46, 52, 64, 62, 63],
       [56, 49, 63, 65, 62, 53, 60, 55]])

In [49]:
b[1:6:2]

array([[51, 61, 53, 52, 61, 63, 68, 54],
       [69, 53, 48, 60, 58, 56, 51, 58],
       [59, 46, 45, 46, 52, 64, 62, 63]])

In [50]:
b[1:6:2, 1:8:3]

array([[61, 61, 54],
       [53, 58, 58],
       [46, 52, 63]])